menu:
  - kadena
  - build
  - pact
  - chainweb
  - marmalade
  - contribute
  - blogchain

pages:
  kadena:
    url: /kadena
    file: /kadena/index.tsx
    children:
      Whykadena:
        url: /why-kadena
        file: /kadena/why-kadena.md
      kda:
        url: /kda
        file: /kadena/kda/index.md
        children:
          managekda:
            url: /manage-kda
            file: /kadena/kda/manage-kda.md
          kdaconcepts:
            url: /kda-concepts
            file: /kadena/kda/kda-concepts.md
      wallets:
        url: /wallets
        file: /kadena/wallets/index.md
        children:
          chainweaver:
            url: /chainweaver
            file: /kadena/wallets/chainweaver/index.md
            children:
              chainweavertroubleshooting:
                url: /chainweaver-troubleshooting
                file: /kadena/wallets/chainweaver/chainweaver-troubleshooting.md
              termsofservice:
                url: /terms-of-service
                file: /kadena/wallets/chainweaver/terms-of-service.md
          kadenaspirekey:
            url: /kadena-spirekey
            file: /kadena/wallets/kadena-spirekey/index.md
          ledger:
            url: /ledger
            file: /kadena/wallets/ledger/index.md
      exchanges:
        url: /exchanges
        file: /kadena/exchanges.md
      client:
        file: /packages/libs/client/README.md
        repo: https://github.com/kadena-community/kadena.js
        url: /client
        children:
          clientapi:
            file: /packages/libs/client/etc/client.api.md
            repo: https://github.com/kadena-community/kadena.js
            url: /api
      clientexamples:
        file: /packages/libs/client-examples/README.md
        repo: https://github.com/kadena-community/kadena.js
        url: /client-examples
      kadenajs:
        file: /packages/libs/kadena.js/README.md
        repo: https://github.com/kadena-community/kadena.js
        url: /kadenajs
      glossary:
        url: /glossary
        file: /kadena/glossary.md
      kadena-faq:
        url: /kadena-faq
        file: /kadena/kadena-faq.md
      resources:
        url: /resources
        file: /kadena/resources.md
      codeofconduct:
        url: /code-of-conduct
        file: /kadena/code-of-conduct.md
  build:
    url: /build
    file: /build/index.tsx
    children:
      quickstart:
        url: /quickstart
        file: /README.md
        repo: https://github.com/kadena-community/getting-started
        children:
          memorywall:
            url: /memorywall
            file: /build/quickstart/memorywall.md
          chainweaver:
            url: /setup-chainweaver
            file: /build/quickstart/setup-chainweaver.md
          testnet:
            url: /testnet-account-setup
            file: /build/quickstart/testnet-account-setup.md
          pactyparrots:
            url: /pacty-parrots
            file: /build/quickstart/pacty-parrots.md
          dapp:
            url: /dapp
            file: /build/quickstart/dapp.md
      kdacli:
        file: /packages/tools/kda-cli/README.md
        repo: https://github.com/kadena-community/kadena.js
        url: /kda-cli
        children:
          kdacliapi:
            file: /packages/tools/kda-cli/etc/kda-cli.api.md
            repo: https://github.com/kadena-community/kadena.js
            url: /api
      cryptographyutils:
        file: /packages/libs/cryptography-utils/README.md
        repo: https://github.com/kadena-community/kadena.js
        url: /cryptography-utils
        children:
          cryptographyutilscryptoapi:
            file: /packages/libs/cryptography-utils/etc/crypto.api.md
            repo: https://github.com/kadena-community/kadena.js
            url: /crypto-api
          cryptographyutilsapi:
            file: /packages/libs/cryptography-utils/etc/cryptography-utils.api.md
            repo: https://github.com/kadena-community/kadena.js
            url: /api
      cookbook:
        url: /cookbook
        file: /build/cookbook/index.md
        children:
          buildcookbook:
            file: /packages/tools/cookbook/README.md
            repo: https://github.com/kadena-community/kadena.js
            url: /cookbook
      guides:
        url: /guides
        file: /build/guides/index.md
        children:
          marmalade:
            url: /marmalade-tutorial
            file: /build/guides/marmalade-tutorial.md
          localapi:
            url: /pact-local-api-queries
            file: /build/guides/pact-local-api-queries.md
          electiondapptutorial:
            url: /election-dapp-tutorial
            file: /build/guides/election-dapp-tutorial/index.md
            children:
              gettingstarted:
                url: /prepare-your-workspace
                file: /build/guides/election-dapp-tutorial/prepare-your-workspace.md
              runningdevnet:
                url: /start-a-local-blockchain
                file: /build/guides/election-dapp-tutorial/start-a-local-blockchain.md
              adminaccount:
                url: /add-admin-account
                file: /build/guides/election-dapp-tutorial/add-admin-account.md
              namespaces:
                url: /define-a-namespace
                file: /build/guides/election-dapp-tutorial/define-a-namespace.md
              keysets:
                url: /define-keysets
                file: /build/guides/election-dapp-tutorial/define-keysets.md
              smart-contract:
                url: /write-a-smart-contract
                file: /build/guides/election-dapp-tutorial/write-a-smart-contract.md
              nominate-candidates:
                url: /nominate-candidates
                file: /build/guides/election-dapp-tutorial/nominate-candidates.md
              voting:
                url: /add-vote-management
                file: /build/guides/election-dapp-tutorial/add-vote-management.md
              gasstation:
                url: /add-a-gas-station
                file: /build/guides/election-dapp-tutorial/add-a-gas-station.md
          rotatedrain:
            url: /safe-rotate-and-drain
            file: /build/guides/safe-rotate-and-drain.md
          safetransfer:
            url: /safe-transfer
            file: /build/guides/safe-transfer.md
      resources:
        url: /resources
        file: /build/resources/index.md
        children:
          kurolayer2:
            url: /kuro-layer-2
            file: /build/resources/kuro-layer-2.md
  pact:
    url: /pact
    file: /pact/index.tsx
    children:
      overview:
        url: /overview
        file: /pact/overview.md
      beginner:
        url: /beginner
        file: /pact/beginner/index.md
        children:
          webeditor:
            url: /web-editor
            file: /pact/beginner/web-editor.md
          helloworld:
            url: /hello-world
            file: /pact/beginner/hello-world.md
          languagebasics:
            url: /language-basics
            file: /pact/beginner/language-basics.md
          modules:
            url: /modules
            file: /pact/beginner/modules.md
          keysets:
            url: /keysets
            file: /pact/beginner/keysets.md
          schemastables:
            url: /schemas-and-tables
            file: /pact/beginner/schemas-and-tables.md
          atomsdk:
            url: /atom-sdk
            file: /pact/beginner/atom-sdk.md
          accountstransfers:
            url: /accounts-and-transfers
            file: /pact/beginner/accounts-and-transfers.md
          contractinteraction:
            url: /contract-interaction
            file: /pact/beginner/contract-interaction.md
          rotatablewallet:
            url: /rotatable-wallet
            file: /pact/beginner/rotatable-wallet.md
          loans:
            url: /loans
            file: /pact/beginner/loans.md
          testsdk:
            url: /test-in-the-sdk
            file: /pact/beginner/test-in-the-sdk.md
      intermediate:
        url: /intermediate
        file: /pact/intermediate/index.md
        children:
          pactjavascript:
            url: /pact-and-javascript
            file: /pact/intermediate/pact-and-javascript.md
          safetyflow:
            url: /safety-using-control-flow
            file: /pact/intermediate/safety-using-control-flow.md
          interfacespact:
            url: /interfaces-with-pact
            file: /pact/intermediate/interfaces-with-pact.md
          builtinfunctions:
            url: /built-in-functions
            file: /pact/intermediate/built-in-functions.md
      reference:
        url: /reference
        file: /pact/reference/index.md
        children:
          restapi:
            url: /rest-api
            file: /pact/reference/rest-api.md
          concepts:
            url: /concepts
            file: /pact/reference/concepts.md
          syntax:
            url: /syntax
            file: /pact/reference/syntax.md
          timeformats:
            url: /time-formats
            file: /pact/reference/time-formats.md
          functions:
            url: /functions
            file: /pact/reference/functions/index.md
            children:
              database:
                url: /database
                file: /pact/reference/functions/database.md
              time:
                url: /time
                file: /pact/reference/functions/time.md
              operators:
                url: /operators
                file: /pact/reference/functions/operators.md
                #repo: https://github.com/kadena-io/pact-5
                #dir: /docs/builtins
              keysets:
                url: /keysets
                file: /pact/reference/functions/keysets.md
              capabilities:
                url: /capabilities
                file: /pact/reference/functions/capabilities.md
              spv:
                url: /spv
                file: /pact/reference/functions/spv.md
              commitments:
                url: /commitments
                file: /pact/reference/functions/commitments.md
              guards:
                url: /guards
                file: /pact/reference/functions/guards.md
              zk:
                url: /zk
                file: /pact/reference/functions/zk.md
              replonlyfunctions:
                url: /repl-only-functions
                file: /pact/reference/functions/repl-only-functions.md
          propertychecking:
            url: /property-checking
            file: /pact/reference/property-checking.md
          propertiesinvariants:
            url: /properties-and-invariants
            file: /pact/reference/properties-and-invariants/index.md
            children:
              numerical:
                url: /numerical
                file: /pact/reference/properties-and-invariants/numerical.md
              bitwise:
                url: /bitwise
                file: /pact/reference/properties-and-invariants/bitwise.md
              objectoperators:
                url: /object-operators
                file: /pact/reference/properties-and-invariants/object-operators.md
              logicaloperators:
                url: /logical-operators
                file: /pact/reference/properties-and-invariants/logical.md
              listoperators:
                url: /list-operators
                file: /pact/reference/properties-and-invariants/list-operators.md
              string:
                url: /string
                file: /pact/reference/properties-and-invariants/string.md
              temporal:
                url: /temporal
                file: /pact/reference/properties-and-invariants/temporal.md
              quantification:
                url: /quantification
                file: /pact/reference/properties-and-invariants/quantification.md
              transactional:
                url: /transactional
                file: /pact/reference/properties-and-invariants/transactional.md
              database:
                url: /database
                file: /pact/reference/properties-and-invariants/database.md
              authorization:
                url: /authorization
                file: /pact/reference/properties-and-invariants/authorization.md
              function:
                url: /function
                file: /pact/reference/properties-and-invariants/function.md
              other:
                url: /other
                file: /pact/reference/properties-and-invariants/other.md
          pacts:
            url: /pacts
            file: /pact/reference/pacts.md
          pactrepl:
            url: /pact-repl-cli
            file: /pact/reference/pact-repl-cli.md
      api:
        url: /api
        file: /pact/api/index.tsx
      pactjs:
        file: /packages/libs/pactjs/README.md
        repo: https://github.com/kadena-community/kadena.js
        url: /pactjs
        children:
          pactjsapi:
            file: /packages/libs/pactjs/etc/pactjs.api.md
            repo: https://github.com/kadena-community/kadena.js
            url: /api
          pactjsutils:
            file: /packages/libs/pactjs/etc/pactjs-utils.api.md
            repo: https://github.com/kadena-community/kadena.js
            url: /utils
      pactjscli:
        file: /packages/tools/pactjs-cli/README.md
        repo: https://github.com/kadena-community/kadena.js
        url: /cli
        children:
          pactjscliapi:
            file: /packages/tools/pactjs-cli/etc/pactjs-cli.api.md
            repo: https://github.com/kadena-community/kadena.js
            url: /api
      pactjsgenerator:
        file: /packages/libs/pactjs-generator/README.md
        repo: https://github.com/kadena-community/kadena.js
        url: /pactjs-generator
        children:
          pactjsgeneratorapi:
            file: /packages/libs/pactjs-generator/etc/pactjs-generator.api.md
            repo: https://github.com/kadena-community/kadena.js
            url: /api
      vscode:
        url: /vscode
        file: /pact/vscode/index.md

  chainweb:
    url: /chainweb
    file: /chainweb/index.tsx
    children:
      compact:
        url: /compact-database
        file: /chainweb/compact-a-database.md
      nodeclient:
        file: /packages/libs/chainweb-node-client/README.md
        url: /node-client
        repo: https://github.com/kadena-community/kadena.js
        children:
          nodeclientapi:
            file: /packages/libs/chainweb-node-client/etc/chainweb-node-client.api.md
            url: /api
            repo: https://github.com/kadena-community/kadena.js
      streamclient:
        file: /packages/libs/chainweb-stream-client/README.md
        url: /stream-client
        repo: https://github.com/kadena-community/kadena.js
        children:
          streamapi:
            file: /packages/libs/chainweb-stream-client/etc/chainweb-stream-client.api.md
            url: /api
            repo: https://github.com/kadena-community/kadena.js
      jsbindings:
        file: /packages/libs/chainwebjs/README.md
        repo: https://github.com/kadena-community/kadena.js
        url: /js-bindings
        children:
          bindingsapi:
            file: /packages/libs/chainwebjs/etc/chainwebjs.api.md
            repo: https://github.com/kadena-community/kadena.js
            url: /api
  marmalade:
    url: /marmalade
    file: /marmalade/index.tsx
    children:
      whatismarmalade:
        url: /what-is-marmalade
        file: /marmalade/what-is-marmalade.md
      quickstart:
        url: /quick-start
        file: /marmalade/mint-with-marmalade.md
      architecture:
        url: /architecture
        file: /marmalade/architecture/index.md
        children:
          ledger:
            url: /ledger
            file: /marmalade/architecture/ledger.md
          policy:
            url: /policy-manager
            file: /marmalade/architecture/policy-manager.md
          sale:
            url: /sale-contracts
            file: /marmalade/architecture/sale-contracts.md
      policies:
        url: /concrete-policies
        file: /marmalade/concrete-policies/index.md
        children:
          collectionpolicy:
            url: /collection-policy
            file: /marmalade/concrete-policies/collection-policy.md
          guardpolicy:
            url: /guard-policy
            file: /marmalade/concrete-policies/guard-policy.md
          nonfungiblepolicy:
            url: /non-fungible-policy
            file: /marmalade/concrete-policies/non-fungible-policy.md
          royaltypolicy:
            url: /royalty-policy
            file: /marmalade/concrete-policies/royalty-policy.md
      auctions:
        url: /auctions
        file: /marmalade/auctions/index.md
        children:
          conventional-auction:
            url: /conventional-auction
            file: /marmalade/auctions/conventional-auction.md
          dutch-auction:
            url: /dutch-auction
            file: /marmalade/auctions/dutch-auction.md
      metadata:
        url: /metadata
        file: /marmalade/metadata/index.md
        children:
          arweavestorage:
            url: /arweave-storage
            file: /marmalade/metadata/arweave-storage.md
          ipfs:
            url: /ipfs
            file: /marmalade/metadata/ipfs.md
      v1:
        url: /marmalade-v1
        file: /marmalade/marmalade-v1/index.md
        children:
          whyv2:
            url: /why-v2
            file: /marmalade/marmalade-v1/why-v2.md
  contribute:
    url: /contribute
    file: /contribute/index.tsx
    children:
      node:
        url: /node
        file: /contribute/node/index.md
        children:
          troubleshooting:
            url: /trouble-shooting-chainweb
            file: /contribute/node/troubleshooting-chainweb.md
          startmining:
            url: /start-mining
            file: /contribute/node/start-mining.md
          interact:
            url: /interact-with-nodes
            file: /contribute/node/interact-with-nodes.md
      ambassadors:
        url: /ambassadors
        file: /contribute/ambassadors/index.md
        children:
          moderator:
            url: /moderator
            file: /contribute/ambassadors/moderator.md
          creator:
            url: /content-creator
            file: /contribute/ambassadors/creator.md
          leader:
            url: /community-channel-leader
            file: /contribute/ambassadors/community-channel-leader.md
      dao:
        url: /kadena-dao
        file: /contribute/kadena-dao.md
      docs:
        url: /docs
        file: /contribute/docs.md
  blogchain:
    url: /blogchain
    file: /blogchain/index.tsx
    children:
      blog2023:
        url: /2023
        file: /blogchain/2023/index.tsx
      blog2022:
        url: /2022
        file: /blogchain/2022/index.tsx
      blog2021:
        url: /2021
        file: /blogchain/2021/index.tsx
      blog2020:
        url: /2020
        file: /blogchain/2020/index.tsx
      blog2019:
        url: /2019
        file: /blogchain/2019/index.tsx
      blog2018:
        url: /2018
        file: /blogchain/2018/index.tsx
