name: Chromatic for Docs
# All pull requests, and
# Workflow dispatch allows you to run this workflow manually from the Actions tab
on:
  push:
    paths:
      - packages/apps/docs/**

jobs:
  chromatic:
    name: Visual Regression Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # ðŸ‘ˆ Required to retrieve git history, needed to determine diffs.

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: PNPM install (install-run-rush)
        run: |
          pnpm install

      - name: Rush Build (internal dependencies)
        run: |
          pnpm --filter @kadena/react-ui... build
          pnpm --filter @kadena/react-components... build

      - name: Publish Storybook
        uses: chromaui/action@v1
        with:
          # ðŸ‘‡ Chromatic projectToken, refer to the manage page to obtain it.
          exitOnceUploaded: true
          buildScriptName: 'build:storybook'
          projectToken: ${{ secrets.DOCS_CHROMATIC_TOKEN }}
          workingDir: /packages/apps/docs
          autoAcceptChanges: 'main'
