name: Docs Cypress tests

on:
  push:
    paths:
      - packages/apps/kadena-docs/*/**

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://pandoc/core:2.9
        with:
          working-directory: packages/apps/kadena-docs
          args: >- # allows you to break string into multiple lines
            --standalone --output=./import/pact/pact-functions.mdx
            ./import/pact/pact-functions.rst

  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          run_install: false
      - name: Rush install (install-run-rush)
        run: |
          node common/scripts/install-run-rush.js install -t @kadena/kadena-docs
      - name: Rush Build
        run: |
          node common/scripts/install-run-rush.js build -t @kadena/kadena-docs
      - name: Create page tree JSON
        run: |
          node ./../../../common/scripts/install-run-rushx.js createtree
        working-directory: packages/apps/kadena-docs
      - name: Cypress tests
        uses: cypress-io/github-action@v5
        with:
          working-directory: packages/apps/kadena-docs
          start: npm run dev
          browser: chrome
          install: false
        env:
          # pass GitHub token to detect new build vs re-run build
          NEXT_PUBLIC_APP_DEV: test
